In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  501.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284341   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.705587   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.884000   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208000   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.625000   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [4]:
# import matplotlib.pyplot as plt
# df.hist(bins=20, figsize=(20,15))

## TRAIN TEST SPLIT

In [5]:
# import numpy as np
#without sklearn 
# def train_test_split(data, test_ratio):
#     np.random.seed(42) #to avoid mutiple shuffling
#     shuffled = np.random.permutation(len(data))
#     test_set_size = int(len(data) * test_ratio)
#     test_indices = shuffled[:test_set_size]
#     train_indices = shuffled[test_set_size:]
#     return data.iloc[train_indices], data.iloc[test_indices]
# train_set, test_set = train_test_split(df, 0.2)
# print("TRAIN DATA:", len(train_set))
# print("TEST DATA:",len(test_set))

In [6]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(df, test_size=0.2, random_state=42)
print("training set:",len(train_set))
print("testing set:",len(test_set))

training set: 404
testing set: 102


In [7]:
from sklearn.model_selection import StratifiedShuffleSplit
# read the documentation for StratifiedShuffleSplit

split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(df, df['CHAS']):
    strat_train_set = df.loc[train_index]
    strat_test_set = df.loc[test_index]

In [8]:
strat_test_set['CHAS'].value_counts()

CHAS
0    95
1     7
Name: count, dtype: int64

In [9]:
strat_train_set['CHAS'].value_counts()

CHAS
0    376
1     28
Name: count, dtype: int64

In [10]:
df = strat_train_set.copy()

In [11]:
df 

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
254  0.04819  80.0   3.64     0  0.392  6.108  32.0  9.2203    1  315   
348  0.01501  80.0   2.01     0  0.435  6.635  29.7  8.3440    4  280   
476  4.87141   0.0  18.10     0  0.614  6.484  93.6  2.3053   24  666   
321  0.18159   0.0   7.38     0  0.493  6.376  54.3  4.5404    5  287   
326  0.30347   0.0   7.38     0  0.493  6.312  28.9  5.4159    5  287   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
155  3.53501   0.0  19.58     1  0.871  6.152  82.6  1.7455    5  403   
423  7.05042   0.0  18.10     0  0.614  6.103  85.1  2.0218   24  666   
98   0.08187   0.0   2.89     0  0.445  7.820  36.9  3.4952    2  276   
455  4.75237   0.0  18.10     0  0.713  6.525  86.5  2.4358   24  666   
216  0.04560   0.0  13.89     1  0.550  5.888  56.0  3.1121    5  276   

     PTRATIO       B  LSTAT  MEDV  
254     16.4  392.89   6.57  21.9  
348     17.0  390.94   5.99  24.5  
476     20.2  396.21  18.68  16.7  
321     19.6  396.90   6.87  23.1  
326     19.6  396.90   6.15  23.0  
..       ...     ...    ...   ...  
155     14.7   88.01  15.02  15.6  
423     20.2    2.52  23.29  13.4  
98      18.0  393.53   3.57  43.8  
455     20.2   50.92  18.13  14.1  
216     16.4  392.80  13.51  23.3  

[404 rows x 14 columns]

In [12]:
df = strat_train_set.drop('MEDV',axis=1)
df_labels = strat_train_set['MEDV'].copy()

## CORRELATIONS

In [13]:
# corr_matrix = df.corr()
# corr_matrix['MEDV'].sort_values(ascending=False)

In [14]:
# from pandas.plotting import scatter_matrix
# attrs = ['MEDV','RM', 'ZN', 'LSTAT']
# scatter_matrix(df[attrs], figsize=(8,8))

In [15]:

# imputer = SimpleImputer(strategy='median')
# imputer.fit(df)
# imputer.statistics_.shape
# X = imputer.transform(df)
# df_tr = pd.DataFrame(X, columns= df.columns)

In [16]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
my_pipeline = Pipeline([('imputer', SimpleImputer(strategy='median')),
                       ('std_scaler', StandardScaler()),
                       ])


In [17]:
df_tr = my_pipeline.fit_transform(df)

In [18]:
df_tr.shape

(404, 13)

In [21]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
# model = LinearRegression()
# model = DecisionTreeRegressor()
model = RandomForestRegressor()
model.fit(df_tr, df_labels)

RandomForestRegressor()

In [22]:
some_data = df.iloc[:10]
some_labels = df_labels.iloc[:10]

In [23]:
prepared_data = my_pipeline.transform(some_data)

In [24]:
model.predict(prepared_data)

array([22.565, 25.85 , 16.495, 23.299, 23.427, 16.547, 24.472, 26.606,
       10.53 , 31.903])

In [25]:
list(some_labels)

[21.9, 24.5, 16.7, 23.1, 23.0, 17.2, 24.4, 27.5, 9.5, 31.6]

In [26]:
from sklearn.metrics import mean_squared_error
df_predictions = model.predict(df_tr)
mse = mean_squared_error(df_labels, df_predictions)
rmse = np.sqrt(mse)

In [27]:
rmse

1.2077306238979735

## CROSS VALIDATION

In [32]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(model, df_tr, df_labels, scoring='neg_mean_squared_error', cv=10)
rmse_scores = np.sqrt(-scores)

In [29]:
rmse_scores

array([2.77967927, 2.92419406, 4.25361265, 2.75711225, 3.38582052,
       2.77575754, 4.59005784, 3.29235323, 3.1646792 , 3.28455238])

In [30]:
def print_scores(scores):
    print("Scores:", scores)
    print("Mean:", scores.mean())
    print("Standard Deviation:", scores.std())

In [31]:
print_scores(rmse_scores)

Scores: [2.77967927 2.92419406 4.25361265 2.75711225 3.38582052 2.77575754
 4.59005784 3.29235323 3.1646792  3.28455238]
Mean: 3.320781892780693
Standard Deviation: 0.598063746577331


## RANDOMDORESTREGERESSOR HAS THE LEAST RMSE SO WE WILL PICK THIS AS OUR MODEL 

In [33]:
# NOW WE WILL SAVE OUR MODEL
from joblib import dump, load
dump(model, "boston-realstate-model.joblib")


['boston-realstate-model.joblib']

## TESTING THE MODEL ON TEST_DATA


In [35]:
x_test = strat_test_set.drop('MEDV', axis=1)
y_test = strat_test_set['MEDV'].copy()
x_test_prepared = my_pipeline.transform(x_test)
final_predcitions = model.predict(x_test_prepared)
final_mse = mean_squared_error(y_test, final_predcitions)
final_rmse = np.sqrt(final_mse)
print(final_rmse)

2.923107156944539


## USING THE MODEL


In [40]:
use_model = load('boston-realstate-model.joblib')
features = np.array([[-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
       -0.23979304, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.86091034]])
use_model.predict(features)

array([22.565])